### ISSUE TITLE
CP-2267 Make Store's `trigger()` awaitable

### ISSUE THREAD

**Issue by evanweible-wf** [Workiva/w_flux#20]
For testing purposes, it'd be nice if the `trigger()` method on a `Store` was awaitable. This would address the need to wait for the async stream event to propagate during tests.

**Comment by evanweible-wf** [comment]
@trentgrover-wf @maxwellpeterson-wf @dustinlessard-wf do we still think this is useful?

**Comment by trentgrover-wf** [comment]
Seems useful, but not high priority
