### ISSUE TITLE
Serverside rendering of Components

### ISSUE THREAD

**Issue by denniskaselow** [Workiva/w_flux#55]
I'd like to use the same code to render my React application server side as well as client side. But it's currently not possible because of the `BatchedRedraws` mixin (because of the `dart:htm`-import).

Are you planning to support server side rendering?

**Comment by maxwellpeterson-wf** [comment]
@denniskaselow Sorry for such a delay in response!

We can definitely add support for server-side rendering. We'd likely offer an alternate entrypoint/import that does not use the `BatchedRedraws` mixin at all.

**Comment by maxwellpeterson-wf** [comment]
Released in version 2.3.0: https://github.com/Workiva/w_flux/releases/tag/2.3.0
