### ISSUE TITLE
CP-2596 : Stores should support a cleanup operation like 'dispose'

### ISSUE THREAD

**Issue by dustinlessard-wf** [Workiva/w_flux#69]
When a module is unloaded, we should also make certain that any cleanup operations are initiated on the store.  It would be nice to enforce this requirement as much as possible with any class that extends 'Store'.

**Comment by rmconsole-wf** [comment]
It looks like you have not included any tickets in the title of this issue. Please create a ticket for this issue, or click <a href='https://w-rmconsole.appspot.com/api/v1/issues/Workiva/w_flux/69/addTicketToTitle'>here</a> to have Rosie create one for you.
