### ISSUE TITLE
WP-4161 CP-2778 triggerOnAction needs to clean up its ActionSubscriptions somehow.

### ISSUE THREAD

**Issue by tomconnell-wf** [Workiva/w_flux#73]
You can see that the returned ActionSubscriptions in https://github.com/Workiva/w_flux/blob/master/lib/src/store.dart#L86 are not captured in a variable and later cancel()ed.  It would avoid memory leaks to do so.

**Comment by rmconsole2-wf** [comment]
It looks like you have not included any tickets in the title of this issue. Please create a ticket for this issue, or click <a href='https://w-rmconsole.appspot.com/api/v1/issues/Workiva/w_flux/73/addTicketToTitle'>here</a> to have Rosie create one for you.
