### ISSUE TITLE
Interceptors should be able to append data to Traces

### ISSUE THREAD

**Issue by dustinlessard-wf** [Workiva/w_flux#87]
Imagine if we had account information appended to traces? Or Network data? Or App data?

**Comment by rm-astro-wf** [comment]
It looks like you have not included any tickets in the title of this issue. Please create a ticket for this issue, or click <a href='https://w-rmconsole.appspot.com/api/v1/issues/Workiva/w_flux/87/addTicketToTitle'>here</a> to have Rosie create one for you.

**Comment by dustinlessard-wf** [comment]
(facepalm) wrong repo
